# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-25 20:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': ('Student',), 'verbose_name_plural': 'Students'},
        ),
    ]
